services:
  smartdns:
    container_name: smartdns
    restart: always
    environment:
      - TZ=CST-8
    image: pymumu/smartdns:latest
    volumes:
      - ./etc:/etc/smartdns
      - ./db:/var/lib/smartdns
      - ./log:/var/log/smartdns
      - /data/smartdns/smartdns_plus_ui.so:/usr/lib/smartdns/smartdns_plus_ui.so:ro
      - /mnt/d/projects/smartdns-plus-ui/wwwroot:/usr/share/smartdns-plus/wwwroot:ro
    network_mode: host
    # If you do not use host network, remove the line above and expose ports instead:
    # ports:
    #   - 6080:6080/tcp
    #   - 6081:6081/tcp
