# Default upstreams
# China group
server 223.5.5.5 -group cn
server 119.29.29.29 -group cn

# Global group
server 8.8.8.8 -group global
server 1.1.1.1 -group global

# Default group for unmatched queries
server 8.8.8.8
server 1.1.1.1
