# Domain rules / address / ip-rules

# Disable IPv6 answers for some domains if needed
domain-rules /domain-set:no_ipv6/ -address #

# Example local PTR handling
address /domain-set:local_ptr/#

# Example direct domains: do not cache and ignore ip-alias
domain-rules /domain-set:direct/ -no-cache -no-ip-alias
