# Domain-set / ip-set definitions

# Disable IPv6 for these domains
domain-set -name no_ipv6 -file /etc/smartdns/rules/no_ipv6.txt

# Local PTR related domains
domain-set -name local_ptr -file /etc/smartdns/rules/local-ptr.txt

# Direct domains example
domain-set -name direct -file /etc/smartdns/rules/direct.txt
